apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web 
  namespace: ntug
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: sc-nas-svm1

