apiVersion: v1
kind: Service
metadata:
  name: ntug 
  namespace: default
spec:
  ports:
  - name: 5000-5000
    port: 80
    protocol: TCP
    targetPort: 5000 
  selector:
    app: nodejs
  type: LoadBalancer
